spring:
  application:
    name: pokedex-notification

azure:
  connection-string: ${AZURE_CONNECTION_STRING}
  hub-path: pokedex
  apns:
    template: "{\"pokemon\":\"$(pokemon)\",\"aps\":{\"badge\":\"#(badge)\",\"alert\": {\"title\":\"$(title)\",\"body\":\"$(body)\"}}}"
  fcm:
    template: "{\"message\":{\"notification\":{\"title\":\"$(title)\",\"body\":\"$(body)\"},\"data\":{\"pokemon\":\"$(pokemon)\"}}}"
    tokens:
      - "d3BaYedCS2OtKJwuM4hvkL:APA91bGvIobvEe5TpPY1MuApyrmhjoXlo_YUeR4pnOZAoBn61e8Uj6QVMXwZSEpneGdNBgx8CtxFASreDgtbDHLQpFwrghMeMePzVhpfXG13mFR6bNfTQsW2pwKmrZOhs5Y7u_m5P0uq"
      - "f54B3AMzQTGXAwqd-Ooutd:APA91bEQcXEJeYk1ujCI657oRVWBv_4MvNzFQWQ5yXL-Liw5TA6J0AT6u-VkuJhM_XLhVnJ_q30aSFPzoPQDLGxvuqMXNIVGan4N5nCdcPfgV7dR3N_Z_gjhcTGlSahMgdhFMq537ogz"

apns:
  device: "68e1f25a1cd05c2bdb43c08d66af3c2e3ee0ecdeea7780dabe41da11ff0d35d2"
  topic: "com.sfeir.lux.pokedex"
  teamId: ${APNS_TEAM_ID}
  keyId: ${APNS_KEY_ID}

fcm:
  tokens:
    - "eV1p5vzNaUJ_vPWanVSJRt:APA91bHzd6ZLvCwne4Or2SbuVpWPWxD5Sjl_iOXR0AuLYKdRjRx9btHVogm9emk1I6N34fyoKEq-LU1TYE7uwQzOH8a6CHYCV4MFLokJIO36h7yT3mdr2xEH5CSMhlOfdZGWVUFXXvYZ"
    - "d3BaYedCS2OtKJwuM4hvkL:APA91bGvIobvEe5TpPY1MuApyrmhjoXlo_YUeR4pnOZAoBn61e8Uj6QVMXwZSEpneGdNBgx8CtxFASreDgtbDHLQpFwrghMeMePzVhpfXG13mFR6bNfTQsW2pwKmrZOhs5Y7u_m5P0uq"
    - "eTPevYG69EwmowAgcHZ0Df:APA91bFwfSoxk_hDSOq7C3ECipNSoH57V46WC_8GqvfpLemKX_bkrZHdFVYdlp87gXnoVKxxkNoSCRZNbHDv_JbUMfFKMv5DsimqzKJLLlpG3CgG7dqDpgLI9k5qx3HWH-CGhv6GDaNQ"
    - "eRQeVFIo0ECIsll_hAESUc:APA91bHsroRCx9kRhVxs06tWFL9IggoI3KK56hRt_bRvNwtJWCEYTz5U8G23Tv6z2QhvlhJeVFOq0DQIugD54CkWa0iZm5cb9ZVxK5YH65tGrUCgm4akiB9zDVfeLsnV8gRHnF2HiqBR"
